const MAX=20;let subject='',classNo=12,semester='1',questions=[],answers={};
const names={bangla:'বাংলা',english:'ইংরেজি',physics:'Physics','life-science':'Life Science',mathematics:'গণিত',geography:'Geography',history:'History',accountancy:'Accountancy','commercial-law':'Commercial Law','business-studies':'Business Studies','computer-science':'Computer Science',costing:'Costing'};
function banks(){try{return JSON.parse(localStorage.getItem('computerQuestionBanksV2')||'{}')}catch{return {}}}
function esc(s){return escapeHtml(s)}
function renderQuestion(q,i){let body='';if(q.type==='mcq')body=`<div class="exam-options">${(q.options||[]).map((o,j)=>`<button class="exam-option" data-i="${i}" data-j="${j}">${String.fromCharCode(65+j)}) ${esc(o)}</button>`).join('')}</div>`;else if(q.type==='true_false')body='<div class="exam-options"><button class="exam-option tf" data-i="'+i+'" data-value="সত্য">সত্য</button><button class="exam-option tf" data-i="'+i+'" data-value="মিথ্যা">মিথ্যা</button></div>';else body=`<div class="text-answer"><textarea id="text-${i}" rows="4" placeholder="তোমার উত্তর লিখো..."></textarea><button class="submit-answer" data-i="${i}">Submit Answer</button></div>`;return `<article class="exam-question" id="q-${i}"><div class="q-top"><span class="q-no">${i+1}</span><span class="q-type">${esc(q.type||'Question')}</span><span class="marks">${q.marks||1} Mark</span></div><h3>${esc(q.question)}</h3>${body}<div class="locked-status" id="status-${i}"></div></article>`}
function lock(i){document.querySelectorAll(`[data-i="${i}"]`).forEach(b=>b.disabled=true);const t=document.getElementById(`text-${i}`);if(t)t.disabled=true}
function choose(i,value,button){if(answers[i])return;const q=questions[i];let correct=false;if(q.type==='mcq')correct=q.options[value]===q.answer;else correct=value===q.answer;answers[i]={value:q.type==='mcq'?q.options[value]:value,correct};document.querySelectorAll(`[data-i="${i}"]`).forEach(b=>b.classList.remove('selected'));button.classList.add('selected');lock(i);document.getElementById(`status-${i}`).textContent='✓ Answer locked'}
function submitText(i){if(answers[i])return;const input=document.getElementById(`text-${i}`);if(!input.value.trim()){alert('উত্তর লিখে Submit Answer চাপুন।');return}const q=questions[i],v=input.value.trim();answers[i]={value:v,correct:String(v).toLowerCase()===String(q.answer||'').trim().toLowerCase()};lock(i);document.getElementById(`status-${i}`).textContent='✓ Answer locked'}
function init(){subject=params().get('subject')||'bangla';classNo=Number(params().get('class')||12);semester=String(params().get('semester')||'1').match(/[1-4]/)?.[0]||'1';const b=banks(),k=`class${classNo}|semester${semester}|${subject}`;questions=Array.isArray(b[k])?b[k].slice(0,MAX):[];document.getElementById('paperTitle').textContent=`Class ${classNo} • Semester ${semester} • ${names[subject]||subject}`;document.getElementById('paperMeta').textContent=`${questions.length} Questions • ${questions.reduce((s,q)=>s+Number(q.marks||1),0)} Total Marks`;document.getElementById('questionList').innerHTML=questions.map(renderQuestion).join('');document.querySelectorAll('.exam-option').forEach(b=>b.onclick=()=>choose(Number(b.dataset.i),b.dataset.j!==undefined?Number(b.dataset.j):b.dataset.value,b));document.querySelectorAll('.submit-answer').forEach(b=>b.onclick=()=>submitText(Number(b.dataset.i)));document.getElementById('submitExam').onclick=finish}
function finish(){if(!questions.length){alert('এই Class + Semester + Subject-এ কোনো question paper নেই।');return}const correct=Object.values(answers).filter(x=>x.correct).length,total=questions.length;sessionStorage.setItem('examResult',JSON.stringify({correct,total,title:`Class ${classNo} • Semester ${semester} • ${names[subject]||subject}`,school:'Computer Room',subject:names[subject]||subject,semester:`Semester ${semester}`}));location.href='result.html'}
init().catch(e=>{console.error(e);document.getElementById('questionList').innerHTML='<div class="card">Question paper load করা যায়নি।</div>'});
