const BANK='practiceQuestionBanksV1';let cls='class5',sem='1',sub='bangla',questions=[];
const NAMES={bangla:'Bengali',english:'English',physics:'Physics','life-science':'Life Science',mathematics:'Mathematics',geography:'Geography',history:'History','computer-science':'Computer Science',accountancy:'Accountancy','commercial-law':'Commercial Law','cost-tax':'Cost Tax','business-studies':'Business Studies','political-science':'Political Science','রাষ্ট্রবিজ্ঞান':'রাষ্ট্রবিজ্ঞান'};
function banks(){try{return JSON.parse(localStorage.getItem(BANK)||'{}')}catch{return {}}}
function key(){return `${cls}|${sem}|${sub}`}
function esc(s){return escapeHtml(s)}
async function init(){cls=params().get('class')||'class5';sem=String(params().get('semester')||'1').match(/[1-4]/)?.[0]||'1';sub=params().get('subject')||'bangla';const b=banks();questions=(b[key()]||[]).slice(0,20);if(!questions.length){try{const r=await fetch(`data/practice/${cls}/semester-${sem}/${sub}.json`);const d=await r.json();questions=(d.questions||[]).slice(0,20)}catch{questions=defaultQuestions(NAMES[sub]||sub)}}questions=questions.slice(0,20);document.getElementById('paperTitle').textContent=`${cls.replace('class','Class ')} • Semester ${sem} • ${NAMES[sub]||sub}`;document.getElementById('paperMeta').textContent=`${questions.length} Questions • Practice only • Answer can be changed`;document.getElementById('questionList').innerHTML=questions.map(render).join('');bind();}

function defaultQuestions(name){const a=[];for(let i=1;i<=20;i++){const q={type:'mcq',question:`${name} Practice Question ${i}`,options:['Option A','Option B','Option C','Option D'],answer:i%4===0?'Option D':i%4===1?'Option A':i%4===2?'Option B':'Option C',marks:1,explanation:'Sample solution: review the topic and select the correct option.'};a.push(q)}return a}
function render(q,i){let body='';if(q.type==='mcq')body=`<div class="practice-options">${(q.options||[]).map((o,j)=>`<button class="practice-option ${q._answer?.chosen===j?(q._answer.correct?'correct':'wrong'):''}" data-q="${i}" data-j="${j}">${String.fromCharCode(65+j)}) ${esc(o)}</button>`).join('')}</div>`;else if(q.type==='true_false')body=`<div class="practice-options"><button class="practice-option ${q._answer?.value==='সত্য'?(q._answer.correct?'correct':'wrong'):''}" data-q="${i}" data-v="সত্য">সত্য</button><button class="practice-option ${q._answer?.value==='মিথ্যা'?(q._answer.correct?'correct':'wrong'):''}" data-q="${i}" data-v="মিথ্যা">মিথ্যা</button></div>`;else body=`<textarea class="practice-text" id="ans-${i}" rows="3" placeholder="তোমার উত্তর লিখো...">${esc(q._answer?.value||'')}</textarea><div class="practice-actions"><button class="check-btn" data-check="${i}">Check Answer</button></div>`;return `<article class="practice-question"><div class="q-top"><span class="q-no">${i+1}</span><span class="q-type">${esc(q.type||'Question')}</span><span class="q-marks">${q.marks||1} Mark</span></div><div class="q-text">${esc(q.question)}</div>${body}<div id="feedback-${i}">${q._answer?`<div class="answer-feedback ${q._answer.correct?'good':'bad'}">${q._answer.correct?'✓ Correct':'✕ Wrong'} — You can change your answer.</div>`:''}</div><button class="solution-btn" data-solution="${i}">Solution</button><div class="solution-box hidden" id="solution-${i}"><strong>Solution:</strong><div>${esc(q.answer||'Answer not added yet.')}</div>${q.explanation?`<p>${esc(q.explanation)}</p>`:''}</div></article>`}
function bind(){document.querySelectorAll('[data-j]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.q),Number(b.dataset.j)));document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>chooseTF(Number(b.dataset.q),b.dataset.v));document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>checkText(Number(b.dataset.check)));document.querySelectorAll('[data-solution]').forEach(b=>b.onclick=()=>document.getElementById('solution-'+b.dataset.solution).classList.toggle('hidden'));}
function choose(i,j){const q=questions[i];q._answer={chosen:j,value:q.options[j],correct:q.options[j]===q.answer};refresh(i)}
function chooseTF(i,v){const q=questions[i];q._answer={value:v,correct:v===q.answer};refresh(i)}
function checkText(i){const input=document.getElementById('ans-'+i);if(!input.value.trim())return alert('উত্তর লিখুন।');const q=questions[i],v=input.value.trim();q._answer={value:v,correct:norm(v)===norm(q.answer)};refresh(i)}
function refresh(i){const node=document.querySelectorAll('.practice-question')[i];const q=questions[i];node.outerHTML=render(q,i);bind()}
function norm(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ')}
document.getElementById('backPractice').onclick=()=>history.back();init().catch(console.error);
